version: 2

sources:
    - name: staging
      database: dataworks-gis
      schema: test_gis

      tables:
          - name: flux_table_partitioned
          - name: geo_table_partitioned
          - name: cities

models:
  - name: stg_city_flux
    description: > 
      add text to explain 
    columns:
      - name: GEO_ID
