CREATE TABLE `dataworks-gis.geos_flux_data.flux_table_partitioned`
(
  lon FLOAT64,
  lat FLOAT64,
  time TIMESTAMP,
  TOA_SW_DWN FLOAT64,
  CLRSKY_SFC_LW_DWN FLOAT64,
  ALLSKY_SFC_LW_DWN FLOAT64,
  CLRSKY_SFC_SW_DWN FLOAT64,
  ALLSKY_SFC_SW_DWN FLOAT64
)
PARTITION BY TIMESTAMP_TRUNC(time, MONTH);